// <auto-generated />
using Govinet_Front_End_Connection_Checker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Govinet_Front_End_Connection_Checker.Migrations
{
    [DbContext(typeof(CheckDbContext))]
    partial class CheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Govinet_Front_End_Connection_Checker.Models.Check", b =>
                {
                    b.Property<string>("prop1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("prop2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prop3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prop4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prop1");

                    b.ToTable("Chekers");
                });
#pragma warning restore 612, 618
        }
    }
}
